name: Basin
main: SOFe\Basin\Basin
description: The ultimate PocketMine-MP load balancing solution
version: 1.1.0
api: 3.0.0-ALPHA3
depend: [FastTransfer]
authors:
- PEMapModder
- SOFe

permissions:
  Basin:
    description: "Allows access to everything Basin has."
    default: false
    children:
      transfer:
        description: "Allows to run the /warn command"
        default: op